repos:
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        name: black
        entry: black
        types_or: [ python, pyi ]
        language: python
        language_version: python3.11

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8
        args: ["--max-line-length=82", "--per-file-ignores=__init__.py:F401", "--exclude=tests/*"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
      - id: mypy
        name: mypy
        exclude: ^tests/
        args: [--ignore-missing-imports ]
        language: python
        language_version: python3.11
        types: [ python ]
        require_serial: true
        verbose: true
        additional_dependencies:
          - "pydantic==1.10.12"

  - repo: https://github.com/commit-check/commit-check
    rev: v0.5.6
    hooks:
#      - id: check-message
      - id: check-branch
      - id: check-author-name
      - id: check-author-email
